#!/bin/env bash 

# Installation control script written by D.Sánchez 2024
# 
# Usage: updates [ list | install ]
#   list    : returns the amount of updates available to install
#   install : install the pending updates as a distro update
#             This option needs to be launched with sudo privileges

IFS=$'\n'

case "$1" in
"list")
    zypper lu > /tmp/updates.txt
    
    NO_UPDATES=`cat /tmp/updates.txt | grep "No se ha encontrado ninguna actualización." | wc -l`
    UPDATES=`cat /tmp/updates.txt | grep -e '^v' | wc -l`
    
    if [[ $NO_UPDATES == "1" ]]; then
      echo "0"
    else
      echo "$UPDATES"
    fi
    ;;
"install")
    /usr/bin/zypper dup
    /usr/bin/zypper refresh
    ;;
*)
  echo "Usage: updates [ install | list ] "
  ;;
esac
